"""add_is_archived_to_posts

Revision ID: c001a06de950
Revises: 544afe255498
Create Date: 2026-06-02 23:12:47.920334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c001a06de950'
down_revision: Union[str, Sequence[str], None] = '544afe255498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('posts', sa.Column(
        'is_archived',
        sa.Boolean(),
        nullable=False,
        server_default=sa.false()   # add this
    ))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'is_archived')
    # ### end Alembic commands ###
